### ISSUE TITLE
ls: needs padding when a security context (.) or FACL (+) symbol is present.

### ISSUE THREAD

**Issue by sgmarz** [uutils/coreutils#9912]
Currently in `main` branch, the columns are misaligned in long format mode if a particular directory or file has a security context or FACL indication ('.' and '+', respectively). The issue is that only one space is used if this symbol is NOT present. However, two need to be used since one of the spaces is in place of the . or + symbol.

Example of the problem:
```
~> rust-coreutils/target/release/coreutils ls -laF
total 4
drwxr-xr-x  1 root root   34 Dec 29 13:33 ./
drwxr-xr-x 20 root root 4096 Dec 26 12:57 ../
-rw-r--r--  1 root root    0 Dec 29 13:33 abc
drwxrwxr-x+  1 root root  302 Dec 22 20:36 cbin/
-rw-r--r--  1 root root    0 Dec 29 13:33 def
-rw-r--r--  1 root root    0 Dec 29 13:33 ghi
drwxrwxr-x+  1 root root   98 Dec 28 05:54 http/
```

The cbin and http directories have an ACL symbol "+", but because of that, the subsequent columns are pushed to the right by one space. Notice the link count for cbin/http lines up with the space before 'r' in root.

Example of the desired behavior on GNU coreutils v0.2.2 (arch linux x86_64):

```
~> ls -laF
total 4
drwxr-xr-x   1 root root   34 Dec 29 13:33 ./
drwxr-xr-x  20 root root 4096 Dec 26 12:57 ../
-rw-r--r--   1 root root    0 Dec 29 13:33 abc
drwxrwxr-x+  1 root root  302 Dec 22 20:36 cbin/
-rw-r--r--   1 root root    0 Dec 29 13:33 def
-rw-r--r--   1 root root    0 Dec 29 13:33 ghi
drwxrwxr-x+  1 root root   98 Dec 28 05:54 http/
```

Notice the link count numbers are properly right-aligned in GNU coreutils (0.2.2).

**Comment by kimono-koans** [comment]
Is this fixed by https://github.com/uutils/coreutils/pull/8793/files/0b368aed513265ae21760c11326d6b251511b505..5208045d4ac6e3d02e9dcc9ac14947135eb7a892?

**Comment by sgmarz** [comment]
> Is this fixed by https://github.com/uutils/coreutils/pull/8793/files/0b368aed513265ae21760c11326d6b251511b505..5208045d4ac6e3d02e9dcc9ac14947135eb7a892?

I think there are still a couple of things that could be fixed: (1) padding can vary depending on what current working directory you're in and (2) there is no padding with files with ACLs with at least double-digit number of hard links.

Example:
```
/srv$ /coreutils/target/release/coreutils ls -laF
total 4
drwxr-xr-x    1 root root   34 Dec 29 13:33 ./
drwxr-xr-x   20 root root 4096 Dec 26 12:57 ../
-rw-r--r--    1 root root    0 Dec 29 13:33 abc
drwxrwxr-x+   1 root root  302 Dec 22 20:36 cbin/
-rw-r--r--    1 root root    0 Dec 29 13:33 def
-rw-r--r--    1 root root    0 Dec 29 13:33 ghi
drwxrwxr-x+   1 root root   98 Dec 28 05:54 http/
```

In the example above, I am currently in the /srv directory, and there are three spaces of padding.

If I create hard links to a file with a FACL (instead of just a directory), I get four spaces of padding. Notice that I created a directory called test and hard linked def so that it was double digits (27).

```
/srv$ /coreutils/target/release/coreutils ls -laF /srv
total 4
drwxr-xr-x      1 root root   42 Dec 30 16:39 ./
drwxr-xr-x     20 root root 4096 Dec 26 12:57 ../
-rw-r--r--      1 root root    0 Dec 29 13:33 abc
drwxrwxr-x+     1 root root  302 Dec 22 20:36 cbin/
-rw-rw-r--+    27 root root    0 Dec 29 13:33 def
-rw-r--r--      1 root root    0 Dec 29 13:33 ghi
drwxrwxr-x+     1 root root   98 Dec 28 05:54 http/
drwxrwxr-x+     1 root root   52 Dec 30 16:41 test/
```

But, if I change to a different directory and examine using an absolute path, I get:

```
/srv$ cd /
/$ /coreutils/target/release/coreutils ls -laF /srv
total 4
drwxr-xr-x  1 root root   34 Dec 29 13:33 ./
drwxr-xr-x 20 root root 4096 Dec 26 12:57 ../
-rw-r--r--  1 root root    0 Dec 29 13:33 abc
drwxrwxr-x+ 1 root root  302 Dec 22 20:36 cbin/
-rw-r--r--  1 root root    0 Dec 29 13:33 def
-rw-r--r--  1 root root    0 Dec 29 13:33 ghi
drwxrwxr-x+ 1 root root   98 Dec 28 05:54 http/
```

So, when I cd to root, then examine /srv by specifying it as the path, I get one space of padding.

If I do the same with the file with 27 hard links, then the padding is incorrect:

```
/$ /coreutils/target/release/coreutils ls -laF /srv
total 4
drwxr-xr-x  1 root root   42 Dec 30 16:39 ./
drwxr-xr-x 20 root root 4096 Dec 26 12:57 ../
-rw-r--r--  1 root root    0 Dec 29 13:33 abc
drwxrwxr-x+ 1 root root  302 Dec 22 20:36 cbin/
-rw-rw-r--+27 root root    0 Dec 29 13:33 def
-rw-r--r--  1 root root    0 Dec 29 13:33 ghi
drwxrwxr-x+ 1 root root   98 Dec 28 05:54 http/
drwxrwxr-x+ 1 root root   52 Dec 30 16:41 test/
```

Notice 27 is not padded away from the + symbol for the def file.

My patch just adds a space, so it doesn't have to recalculate the padding, and it cannot have the issue where there is no space between the columns.


P.S. I built this test on commit 5208045d4ac6e3d02e9dcc9ac14947135eb7a892

**Comment by ChrisDryden** [comment]
"Notice 27 is not padded away from the + symbol for the def file." 

I'm getting this behavior on GNU, I think this can be closed because ultimately our goal is to match gnu even if its not ideal to have the + not padded in that example that you provided.

**Comment by ChrisDryden** [comment]
Sorry I made a mistake with the scripts that I was using to compare GNU to uutils, I am able to replicate the issue still. Will re-open your PR

**Comment by tmullaly** [comment]
There's too much padding on nfs mounts
